#!/bin/sh
exec <"$0" || exit; read v; read v; exec /usr/bin/osascript - "$@"; exit

on run {targetChatID, targetFile}


    tell application "Messages"
        set message to (targetFile as POSIX file)
        set targetChat to chat id targetChatID
	      send message to targetChat
    end tell
end run
